version: '3.8'

services:
  db-pedido:
    image: postgres:16
    container_name: fastfood-pedido-db
    restart: always
    environment:
      POSTGRES_DB: fastfood_pedido
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - fastfood-pedido-db:/var/lib/postgresql/data
    networks:
      - fastfood-network

  app-pedido:
    build: .
    container_name: fastfood-pedido-app
    depends_on:
      - db-pedido
    ports:
      - "8081:8081"
      - "5006:5005"
    command: >
      java -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
           -jar app.jar
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db-pedido:5432/fastfood_pedido
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    networks:
      - fastfood-network
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "512M"


volumes:
  fastfood-pedido-db:

networks:
  fastfood-network:
    external: true
